In [48]:
import torch
import torch.nn as nn
import math
import matplotlib.pyplot as plt


In [62]:
input = torch.Tensor([[2,2], [3,1]])
grad = torch.Tensor([[2,2], [3,1]])

input_x = input[:,0]
input_y = input[:,1]

print(f'{input_x}')

for x, y in input:
    print(x,y)

tensor([2., 3.])
tensor(2.) tensor(2.)
tensor(3.) tensor(1.)


In [68]:
input = torch.Tensor([[2,4], [3,1], [2,4], [3,1]])
grad = torch.Tensor([[2,5], [3,1]], [2,4], [3,1])

print(input)

for x, y, dx, dy in input, grad:
    print(x,y, dx, dy)


tensor([[2., 4.],
        [3., 1.]])


ValueError: not enough values to unpack (expected 4, got 2)

In [2]:
x = torch.ones(10, requires_grad=True)
weights = {'x':x}

y = x**2
z = x**3



l = (x**4).sum()

first_derivative = torch.autograd.grad(l, x, retain_graph=True, create_graph=True)[0]
print(first_derivative)
second_derivative = torch.autograd.grad(first_derivative, x)[0]
print(first_derivative)
print(second_derivative)

tensor([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.], grad_fn=<MulBackward0>)


RuntimeError: grad can be implicitly created only for scalar outputs

In [15]:
x = torch.ones(10, requires_grad=True)
weights = {'x':x}

y = x**2
z = x**3



l = (x**4).sum()
l.backward()
g_x = x.grad.data

#g_x.requires_grad = True ## Adds it to the computation graph!
print(f'g_x = x.grad = {x.grad}\n')

x.grad.zero_()

print(f'g_x = x.grad = {x.grad}\n')
#weights['g_x'] = g_x
#print(f'weights = {weights}\n')

J = 0*x.sum() #(x**4).sum() + (y + z + g_x).sum()
J.backward()
print(f'g_x = x.grad = {x.grad}\n')


g_x = x.grad = tensor([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

g_x = x.grad = tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

g_x = x.grad = tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])



RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling .backward() or autograd.grad() the first time.

WIN WIN WIN
WIN WIN WIN
WIN WIN WIN
WIN WIN WIN
WIN WIN WIN
WIN WIN WIN
WIN WIN WIN
WIN WIN WIN
WIN WIN WIN
WIN WIN WIN
