In [1]:
import torch
from torch.autograd import grad
import torch.nn as nn


In [2]:



# Create some dummy data.
x = torch.ones(1, 1, requires_grad=True)
gt = torch.ones_like(x) * 2 - 1  # "ground-truths" 

print(x.size())
# We will use MSELoss as an example.
loss_fn = nn.MSELoss()

# Do some computations.
v = x + 1
y = v ** 2

# Compute loss.
loss = loss_fn(y, gt)

print(f'Loss: {loss}')

# Now compute gradients:
d_loss_dx = grad(outputs=loss, inputs=x)[0]
print(f'dloss/dx:\n {d_loss_dx}')

torch.Size([1, 1])
Loss: 9.0
dloss/dx:
 tensor([[24.]])


In [33]:
a = torch.rand(3,3,2)
m = nn.Softmax()
a = m(a)
print(a[0])

a = a[:,:,0]
print(a)

print(a.unsqueeze(2))

a[:,0]

TypeError: forward() takes 2 positional arguments but 3 were given

In [27]:
test = torch.rand(3,3,1)
print(test)
test = test[:,:,0]
test = test[None]
test

tensor([[[0.9776],
         [0.4367],
         [0.0216]],

        [[0.8505],
         [0.3132],
         [0.6487]],

        [[0.1859],
         [0.8875],
         [0.3024]]])


tensor([[[0.9776, 0.4367, 0.0216],
         [0.8505, 0.3132, 0.6487],
         [0.1859, 0.8875, 0.3024]]])